from pydantic import BaseModel, Field
from typing import Any

class DocumentSchema(BaseModel):
    """
    Schema for the document provided by the user.
    """
    file_name: str = Field(..., description="The name of the file")
    metadata: dict[str, Any] = Field(..., description="The metadata of the file")
    chunks: list[str] = Field(..., description="The chunks of the file")
    embeddings: list[list[float]] = Field(..., description="Embeddings generated by the embedding model")
